let counter = 0;

/** Always-increasing, unique per test run. */
function uniqueSuffix(): string {
  counter += 1;
  return `${Date.now()}-${process.pid}-${counter}`;
}

export interface ProductPayload {
  title: string;
  price: number;
  description: string;
  image: string;
  category: string;
}

export function buildProduct(overrides: Partial<ProductPayload> = {}): ProductPayload {
  return {
    title: `Automated Test Product ${uniqueSuffix()}`,
    price: 19.99,
    description: 'Product generated by the automated test suite.',
    image: 'https://i.pravatar.cc',
    category: 'electronic',
    ...overrides,
  };
}

export function buildClothingItems(count = 3): ProductPayload[] {
  return Array.from({ length: count }, (_, i) =>
    buildProduct({
      category: "men's clothing",
      title: `Automated Clothing Item ${uniqueSuffix()}-${i}`,
      price: 29.99,
    })
  );
}